### ISSUE TITLE
ResultIteratorType Instance returning a Not valid resolved type for field "count" when processed

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/tdbm-graphql#16]
Hello TCM,

When I make a GraphQL request that expects a ResultIteratorType in return, my client responds with this error:
`GraphQL error: Not valid resolved type for field "count": (no details available)`

I know it has been fixed in the passed, but it reappeared when client app was updated to Angular 5 and Apollo 2 (in order to support Mutation calls).

Thanks for the good work !

**Comment by WizMik** [comment]
I believe the correction was to cast the result as an int, wich is not the case in the source files. Maybe the correction hasn't been tagged ?

**Comment by Zheness** [comment]
Hey,
I just pushed the pull-request #17 in order to fix that. Waiting for validation.
Thanks

**Comment by moufmouf** [comment]
Ok, fixed at the core of TDBM (see #17)
