### ISSUE TITLE
How to add Field annotation to relations ?

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/tdbm-graphql#34]
Hi there ! TDBM is wonderful, so is GraphQLite.

One thing that appears to be missing though is the ability to set annotations on relationship getters that TDBM generates in the abstract classes.
The only way for now is to overload the getter from the abstract class and add some annotation in the code.

One way to do it would be to add a reference to the foreign key name in the comment section of the table or the field used for the foreign key, along with the desired annotation (because sadly, FKs don't handle comments).

Cheers !

**Comment by moufmouf** [comment]
I see!

Something like a `@TheCodingMachine\GraphQLite\Annotations\ReverseField` annotation in the column of the "source" table?

**Comment by WizMik** [comment]
Looks okay, but I guess you'll have to create "Reverse" annotations for Logged, Right, FailWith etc...

**Comment by WizMik** [comment]
And creating a new anno in GraphQL only to serve TDBM integration might not be the good approach.
Maybe a simple spelling of the anno would do the trick, something like `@TheCodingMachine\GraphQLite\Annotations\Field:RefType` ?

Another wonderful feature would be the ability of filling the annotation params via comments.

For example, let's take a `company_product` table referencing a `company` table via the `company_product.companyID` field.
We could invoke the attributes of `@Field` annotation by commenting the `company_product.companyID` like so:

`@TheCodingMachine\GraphQLite\Annotations\Field(name='products', outputType='someThing'):Company` in the `company_product.companyID` field.

It's just a picture I get of how exending this ecosystem, but maybe not the best way of doing it.
And you might need to figure out how to do it on many to many relations... (maybe by commenting fields in the joint table)

Cheers ! :+1:

**Comment by WizMik** [comment]
And another wontherfull feature would be the ability of aliasing the fileds, like so :
`/**
* @Field('members')
* @return CompanyMembers[]
public function getCompanyMembers (): ResultIterator { ... }`
...and via TDBM, in comments like so :
`#@TheCodingMachine\GraphQLite\Annotations\Field:id`

**Comment by WizMik** [comment]
Any news on this matter ? Cheers !

**Comment by WizMik** [comment]
Just found out... you already implemented this !
So when adding an annotation on a column, if it has a FK, it adds the annotations to the relation getter in TDBM.... Clever !

Anyway, thanks !
