### ISSUE TITLE
GraphQLTypeGenerator does not handle Json columns

### ISSUE THREAD

**Issue by Fooriva** [thecodingmachine/tdbm-graphql#6]
Line 284 in GraphQLTypeGenerator "// TODO: how to handle JSON properties???"
=> no error handling / fallback for JSON columns "Cannot map PHP type 'array' to any known GraphQL type." when generating Beans / Daos

**Comment by moufmouf** [comment]
Fixed.
Now, JSON columns are ignored (this is the only thing we can sanely do since GraphQL does not allow untyped types)
See #13
