### ISSUE TITLE
HOW TO SETUP AND USE 

### ISSUE THREAD

**Issue by Koredeoluwafemi** [thecodingmachine/tdbm-graphql#7]
Hello thecodingmachine,

I am Korede, a developer who just picked interest in graphql due to its awesome features. I recently came across this wonderful package of yours but I have been unable to use it as there is no instructions on your github on how to use it. I will appreciate if you can show me how to setup this and also use.

Thanks.

**Comment by moufmouf** [comment]
It's coming really late (1year and a half!) but the package is finally having a proper documentation: https://graphqlite.thecodingmachine.com/
